- hosts: localhost
  gather_facts: false

  tasks:
    - name: Load variables
      ansible.builtin.include_vars: vars.yaml

    - name: Create OpenStack networks
      openstack.cloud.network:
        cloud: "{{ cloud_name }}"
        state: present
        name: "{{ instance_name }}-{{ item.name }}-net"
      loop: "[ {{ spine }} ] + {{ leaves }}"
    
    - name: Create OpenStack subnets
      openstack.cloud.subnet:
        cloud: "{{ cloud_name }}"
        state: present
        name: "{{ instance_name }}-{{ item.name }}-subnet"
        network_name: "{{ instance_name }}-{{ item.name }}-net"
        cidr: "{{ item.cidr }}"
        enable_dhcp: yes
        dns_nameservers: "{{ item.dns_nameservers | default([]) }}"
        gateway_ip: "{{ item.cidr | ansible.utils.nthhost(1) }}"
      loop: "[ {{ spine }} ] + {{ leaves }}"

    - name: Create the OpenStack external router
      openstack.cloud.router:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-external-router"
        network: "{{ external_network }}"
        interfaces:
          - "{{ instance_name }}-{{ spine.name }}-subnet"

    - name: Create the OpenStack Security Group
      openstack.cloud.security_group:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-sg"

    - name: Create OpenStack Security Group rule to allow SSH
      openstack.cloud.security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ instance_name }}-sg"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22

    - name: Create OpenStack Security Group rule to allow BGP peering
      openstack.cloud.security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ instance_name }}-sg"
        protocol: tcp
        port_range_min: 179
        port_range_max: 179

    - name: Create OpenStack Security Group rule to allow ICMP
      openstack.cloud.security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ instance_name }}-sg"
        protocol: icmp

    - name: Create OpenStack Security Group rule to allow DNS
      openstack.cloud.security_group_rule:
        cloud: "{{ cloud_name }}"
        security_group: "{{ instance_name }}-sg"
        protocol: udp
        port_range_min: 53
        port_range_max: 53

    - name: Create the Spine Gateway VM ports connected to the leaves
      openstack.cloud.port:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-{{ spine.name }}-gateway-{{ item.name }}-port"
        network: "{{ instance_name }}-{{ item.name }}-net"
        fixed_ips:
          - ip_address: "{{ item.cidr | ansible.utils.nthhost(10) }}"
      loop: "{{ leaves }}"

    - name: Build a variable for the Spine network name
      set_fact:
        spine_network_name: "{{ instance_name }}-{{ spine.name }}-net"

    - name: Build a variable for the Spine port names
      set_fact:
        spine_network_name: "{{ spine_network_name | default([]) }} + "
      loop: "{{ leaves }}"

    - name: Create a fact to list all the NICS for the Spine Gateway VM
      set_fact:
        #spine_gw_vm_nics: "{{ spine_gw_vm_nics | default({{ instance_name }}-{{ spine.name }}-net) }} + {{ instance_name }}-{{ spine.name }}-gateway-{{ item.name }}-port"
        spine_gw_vm_nics: "{{ spine_gw_vm_nics | default([{'net-name': spine_network_name}]) + [{'port-name': item }] }}"
      loop: "{{ spine_port_names }}"

    - debug: msg="{{ spine_gw_vm_nics }}"

    - fail: msg="stop"

    - name: Create the Spine Gateway VM
      openstack.cloud.server:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-{{ spine.name }}-gateway"
        image: "{{ image }}"
        key_name: "{{ keypair | mandatory }}"
        security_groups:
          - "{{ {{ instance_name }}-sg }}"
        delete_fip: yes
        flavor: "{{ flavor }}"
        nics: "{{ spine_gw_vm_nics }}"
