- hosts: localhost
  gather_facts: false

  tasks:
    - name: Load variables
      ansible.builtin.include_vars: vars.yaml

    - name: Create OpenStack networks
      openstack.cloud.network:
        cloud: "{{ cloud_name }}"
        state: present
        name: "{{ instance_name }}-{{ item.name }}-net"
      loop: "{{ all_networks }}"

    - name: Create OpenStack subnets
      openstack.cloud.subnet:
        cloud: "{{ cloud_name }}"
        state: present
        name: "{{ instance_name }}-{{ item.name }}-subnet"
        network_name: "{{ instance_name }}-{{ item.name }}-net"
        cidr: "{{ item.cidr }}"
        enable_dhcp: yes
        dns_nameservers: "{{ item.dns_nameservers | default([]) }}"
        gateway_ip: "{{ item.cidr | ansible.utils.nthhost(1) }}"
      loop: "{{ all_networks }}"

    - name: Create the OpenStack external router
      openstack.cloud.router:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-external-router"
        network: "{{ external_network }}"
        interfaces:
          - "{{ instance_name }}-{{ spine.name }}-subnet"

    - name: Create VM ports on the spine network
      openstack.cloud.port:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-{{ item.name }}-spine-port"
        network: "{{ instance_name }}-{{ spine.name }}-net"
        fixed_ips:
          - ip_address: "{{ item.spine_ip }}"
        port_security_enabled: false
      loop: "{{ all_networks }}"
      register: spine_ports_result

    - name: Create map of network name to spine port uuid
      set_fact:
        spine_ports: '{{ dict(spine_ports_result.results | map("json_query", "[item.name, id]") | list) }}'

    - name: Create VM ports on leaf networks
      openstack.cloud.port:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-{{ item.name }}-leaf-port"
        network: "{{ instance_name }}-{{ item.name }}-net"
        fixed_ips:
          - ip_address: "{{ item.cidr | ansible.utils.nthhost(1) }}"
        port_security_enabled: false
      loop: "{{ leaves }}"
      register: leaf_ports_result

    - name: Create map of network name to leaf port uuid
      set_fact:
        leaf_ports: '{{ dict(leaf_ports_result.results | map("json_query", "[item.name, id]") | list) }}'

    - name: Create the spine gateway VM
      openstack.cloud.server:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-{{ spine.name }}-gateway"
        image: "{{ image }}"
        key_name: "{{ keypair | mandatory }}"
        flavor: "{{ flavor }}"
        nics: "{{ [ { 'port-id': spine_ports['spine'] } ] }}" # Spine was the first VM port we created
        auto_ip: false
        security_groups: []
        timeout: 600
      async: 600
      poll: 0
      register: spine_vm_create

    - name: Create the leaf gateway VMs
      openstack.cloud.server:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-{{ item.name }}-gateway"
        image: "{{ image }}"
        key_name: "{{ keypair | mandatory }}"
        flavor: "{{ flavor }}"
        nics: "{{ [ {'port-id': spine_ports[item.name] },
                    {'port-id': leaf_ports[item.name] } ] }}"
        auto_ip: false
        security_groups: []
        timeout: 600
      loop: "{{ leaves }}"
      async: 600
      poll: 0
      register: leaf_vm_create

    - name: Wait for spine gateway VM creation
      async_status:
        jid: "{{ spine_vm_create.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 20
      delay: 30

    - name: Wait for leaf gateway VMs creation
      async_status:
        jid: "{{ async_result_item.ansible_job_id }}"
      loop: "{{ leaf_vm_create.results }}"
      loop_control:
        loop_var: async_result_item
      register: job_result
      until: job_result.finished
      retries: 20
      delay: 30
