- hosts: localhost
  gather_facts: false

  tasks:
    - name: Load variables
      ansible.builtin.include_vars: vars.yaml

    - name: Delete the Spine Gateway VM
      openstack.cloud.server:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-{{ spine.name }}-gateway"
        state: absent

    - name: Delete the OpenStack external router
      openstack.cloud.router:
        cloud: "{{ cloud_name }}"
        state: absent
        name: "{{ instance_name }}-external-router"

    - name: Delete resources for network {{ item.name }}
      include_tasks: teardown_network.yaml
      loop: "{{ all_networks }}"
