- hosts: localhost
  gather_facts: false

  tasks:
    - name: Load variables
      ansible.builtin.include_vars: vars.yaml

    - name: Delete all gateway VMs
      openstack.cloud.server:
        cloud: "{{ cloud_name }}"
        name: "{{ instance_name }}-{{ item.name }}-gateway"
        state: absent
      loop: "{{ all_networks }}"
      async: 600
      poll: 0
      register: delete_vms

    - name: Wait for gateway VM deletion
      async_status:
        jid: "{{ delete_vm.ansible_job_id }}"
      loop: "{{ delete_vms.results }}"
      loop_control:
        loop_var: delete_vm
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 20

    - name: Delete the OpenStack external router
      openstack.cloud.router:
        cloud: "{{ cloud_name }}"
        state: absent
        name: "{{ instance_name }}-external-router"

    - name: Delete resources for network {{ item.name }}
      include_tasks: teardown_network.yaml
      loop: "{{ all_networks }}"
